# Generated by Django 5.2.5 on 2025-08-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendBoxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_payment_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('callback_url', models.URLField(blank=True, max_length=255, null=True)),
                ('method_payment_id', models.CharField(blank=True, null=True)),
                ('customer_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_number', models.CharField(max_length=14)),
                ('customer_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customer_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('customer_address', models.CharField(blank=True, null=True)),
                ('customer_description', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('delete', 'Delete')], default='active', max_length=15)),
                ('pay_status', models.CharField(choices=[('pending', 'Pending'), ('unpaid', 'Unpaid'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('transaction_id', models.CharField(blank=True, null=True)),
                ('invoice_trxn', models.CharField(blank=True, null=True)),
                ('extras', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SendBoxPaymentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_id', models.CharField(blank=True, max_length=50, null=True)),
                ('trx_uuid', models.CharField(editable=False, max_length=50, unique=True)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_number', models.CharField(max_length=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank')], max_length=20)),
                ('payment_details', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('rejected', 'Rejected'), ('delete', 'Delete')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
