# Generated by Django 5.2.5 on 2025-08-25 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_sendbox', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendboxinvoice',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sendbox_invoices', to='authentication.merchant'),
        ),
        migrations.AddField(
            model_name='sendboxpaymenttransfer',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sendbox_payment_transfer', to='authentication.merchant'),
        ),
    ]
