# Generated by Django 5.2.5 on 2025-08-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sendbox', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendboxinvoice',
            name='invoice_trxn',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sendboxinvoice',
            name='method_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sendboxinvoice',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
