# Generated by Django 5.2.5 on 2025-08-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sendbox', '0003_alter_sendboxinvoice_invoice_trxn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendboxinvoice',
            name='customer_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
