# Generated by Django 5.2.5 on 2025-08-13 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransfer',
            name='trx_uuid',
            field=models.UUIDField(default=uuid.UUID('ce2292ae-89f2-4ace-98cc-376654582336'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='trx_uuid',
            field=models.CharField(default=uuid.UUID('93fa580e-35b4-4899-a045-0a85fb933289'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='trx_uuid',
            field=models.UUIDField(default=uuid.UUID('4bb1fbfc-a4c5-4eab-8cc4-3f38858201f7'), editable=False, unique=True),
        ),
    ]
