# Generated by Django 5.2.5 on 2025-08-12 08:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransfer',
            name='transfer_id',
            field=models.UUIDField(default=uuid.UUID('1e65fbac-e104-4cb3-a7a3-32c1dabc4949'), editable=False, unique=True),
        ),
    ]
