# Generated by Django 5.2.5 on 2025-08-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
