# Generated by Django 5.2.4 on 2025-08-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_uid',
            field=models.UUIDField(default='284cc84db8f04ee19a39bf225c907e83', editable=False),
        ),
        migrations.AlterField(
            model_name='paymenttransfer',
            name='transfer_id',
            field=models.UUIDField(default='ff26e4cabe894011a5033b35fa9c926c', editable=False),
        ),
    ]
