# Generated by Django 5.2.5 on 2025-08-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='callback_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
