# Generated by Django 5.2.5 on 2025-08-13 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_paymenttransfer_trx_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransfer',
            name='trx_uuid',
            field=models.CharField(default=uuid.UUID('7b1f02ed-e00b-4b46-84ba-bfe9d59ac907'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='trx_uuid',
            field=models.CharField(default=uuid.UUID('bde3b2c4-6962-42b1-8eeb-7109d7125c39'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='trx_uuid',
            field=models.CharField(default=uuid.UUID('e2212033-ec65-441d-bf97-105f5320cfe7'), editable=False, unique=True),
        ),
    ]
