# Generated by Django 5.2.5 on 2025-08-12 09:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_paymenttransfer_transfer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransfer',
            name='transfer_id',
            field=models.UUIDField(default=uuid.UUID('7e5a6693-fbf1-4b5d-a555-63e05524638c'), editable=False, unique=True),
        ),
    ]
