# Generated by Django 5.2.5 on 2025-08-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_invoice_callback_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
