# Generated by Django 5.2.5 on 2025-08-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invoice_callback_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='data',
        ),
    ]
