# Generated by Django 5.2.4 on 2025-08-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_invoice_payment_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_uid',
            field=models.UUIDField(default='804a7025801c4e04a4ffd1a2b05a84c7', editable=False),
        ),
        migrations.AlterField(
            model_name='paymenttransfer',
            name='transfer_id',
            field=models.UUIDField(default='52f0df40f7ee4a6387932bfc09981855', editable=False),
        ),
    ]
