# Generated by Django 5.2.5 on 2025-08-13 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_paymenttransfer_trx_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransfer',
            name='trx_uuid',
            field=models.CharField(default=uuid.UUID('1f54fa57-2348-4484-aa76-9c1625b58c9d'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='trx_uuid',
            field=models.CharField(default=uuid.UUID('72b2cfdf-6bab-4ba3-aeb4-4cf16adb7ffb'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='trx_uuid',
            field=models.CharField(default=uuid.UUID('a401b773-6f0a-405e-8d07-f77a285c80d7'), editable=False, unique=True),
        ),
    ]
