# Generated by Django 5.2.5 on 2025-09-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_paymenttransfer_confirm_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransfer',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
