# Generated by Django 5.2.5 on 2025-08-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoice_data_alter_invoice_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='data',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
