# Generated by Django 5.2.5 on 2025-08-13 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_paymenttransfer_trx_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransfer',
            name='trx_uuid',
            field=models.CharField(default=uuid.UUID('4830efde-cb1b-4e4d-9f8d-2bce2678a29e'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='trx_uuid',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='trx_uuid',
            field=models.CharField(default=uuid.UUID('10fc5db4-9b35-4974-9516-a31cf4b06369'), editable=False, unique=True),
        ),
    ]
