# Generated by Django 5.2.5 on 2025-08-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_invoice_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='data',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
