# Generated by Django 5.2.5 on 2025-08-12 09:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_paymenttransfer_transfer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransfer',
            name='transfer_id',
            field=models.UUIDField(default=uuid.UUID('8b985def-a26d-4771-b5ec-1c0d7bea880f'), editable=False, unique=True),
        ),
    ]
