# Generated by Django 5.2.5 on 2025-08-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_paymenttransfer_trx_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransfer',
            name='trx_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransfer',
            name='trx_uuid',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='trx_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='trx_uuid',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
