# Generated by Django 5.2.5 on 2025-08-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_paymenttransfer_trx_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransfer',
            name='trx_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransfer',
            name='trx_uuid',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='trx_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='trx_uuid',
            field=models.CharField(default='9f043be8dab343c1af28155cb2132069', editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='trx_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='trx_uuid',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
