# Generated by Django 5.2.5 on 2025-08-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_paymenttransfer_trx_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='trx_uuid',
            field=models.CharField(default='9885798e3ba943de8aea922c11470dcf', editable=False, max_length=50, unique=True),
        ),
    ]
