# Generated by Django 5.2.5 on 2025-08-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_wallettransaction_trx_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='trx_uuid',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
