# Generated by Django 5.2.5 on 2025-08-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_wallettransaction_trx_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_payment_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
