# Generated by Django 5.2.5 on 2025-08-13 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0010_alter_invoice_invoice_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal', to='authentication.userpaymentmethod'),
        ),
    ]
