# Generated by Django 5.2.5 on 2025-08-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_withdrawrequest_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
