# Generated by Django 5.2.5 on 2025-08-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_wallettransaction_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='net_amount',
        ),
    ]
