# Generated by Django 5.2.5 on 2025-08-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_withdrawrequest_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransfer',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='paymenttransfer',
            name='net_amount',
        ),
    ]
