# Generated by Django 5.2.5 on 2025-08-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_paymenttransfer_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('delete', 'Delete')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='paymenttransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('rejected', 'Rejected'), ('delete', 'Delete')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('rejected', 'Rejected'), ('delete', 'Delete')], default='pending', max_length=10),
        ),
    ]
