# Generated by Django 5.2.5 on 2025-08-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_invoice_status_alter_paymenttransfer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='ip_address',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
