# Generated by Django 5.2.5 on 2025-08-17 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_basepaymentgateway'),
        ('core', '0017_wallettransaction_current_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='authentication.basepaymentgateway'),
        ),
    ]
