# Generated by Django 5.2.5 on 2025-08-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='api_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='secret_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
