# Generated by Django 5.2.4 on 2025-08-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbrand',
            name='brand_key',
            field=models.UUIDField(default='fbfd008307b447eea2b7a255b8599669', editable=False),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='wallet_id',
            field=models.UUIDField(default='b4e66765a9254eb5aabb1983b07e5e84', editable=False, unique=True),
        ),
    ]
