# Generated by Django 5.2.5 on 2025-08-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymentmethod',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
