# Generated by Django 5.2.5 on 2025-08-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepaymentgateway',
            name='method',
            field=models.CharField(choices=[('bkash', 'bkash'), ('bkash-agent', 'bkash-agent'), ('bkash-personal', 'bkash-personal'), ('nagad', 'nagad'), ('nagad-agent', 'nagad-agent'), ('nagad-personal', 'nagad-personal'), ('rocket', 'rocket'), ('rocket-agent', 'rocket-agent'), ('rocket-personal', 'rocket-personal'), ('bkash-sendbox', 'bkash-sendbox'), ('nagad-sendbox', 'nagad-sendbox'), ('rocke-sendboxt', 'rocket-sendbox'), ('bank', 'bank'), ('crypto', 'crypto')], max_length=20),
        ),
    ]
