# Generated by Django 5.2.5 on 2025-08-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='mobile_number',
        ),
        migrations.AlterField(
            model_name='merchant',
            name='domain_name',
            field=models.URLField(blank=True, null=True),
        ),
    ]
