# Generated by Django 5.2.5 on 2025-08-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='fees',
            new_name='deposit_fees',
        ),
        migrations.AddField(
            model_name='merchant',
            name='payout_fees',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
        ),
        migrations.AddField(
            model_name='merchant',
            name='withdraw_fees',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
        ),
    ]
