# Generated by Django 5.2.5 on 2025-09-03 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_fees_merchant_deposit_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsdevicekey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_device_key', to=settings.AUTH_USER_MODEL),
        ),
    ]
