# Generated by Django 5.2.5 on 2025-08-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_merchant_merchant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='merchant_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
