# Generated by Django 5.2.5 on 2025-08-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userpaymentmethod_is_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePaymentGateWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bkash', 'bkash'), ('nagad', 'nagad'), ('rocket', 'rocket'), ('bank', 'bank'), ('crypto', 'crypto')], max_length=20)),
                ('method_uuid', models.CharField(editable=False, max_length=255, unique=True)),
                ('base_url', models.URLField(max_length=255)),
                ('app_key', models.CharField(max_length=255)),
                ('app_secret', models.CharField(max_length=255)),
                ('app_username', models.CharField(max_length=50)),
                ('app_password', models.CharField(max_length=500)),
                ('callback_base_url', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
