# Generated by Django 5.2.5 on 2025-08-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_merchant_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='email',
        ),
    ]
