# Generated by Django 5.2.5 on 2025-08-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_basepaymentgateway_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepaymentmessage',
            name='messager_receiver',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
