# Generated by Django 5.2.4 on 2025-08-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userbrand_brand_key_alter_userwallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userbrand',
            name='brand_key',
            field=models.UUIDField(default='9f3eeb8aa8314f7daa0ada5cad75e1b5', editable=False),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='wallet_id',
            field=models.UUIDField(default='5a29e02c99554c478f0750a9d9e06a98', editable=False, unique=True),
        ),
    ]
