# Generated by Django 5.2.5 on 2025-08-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_merchant_api_key_alter_merchant_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbrand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
