# Generated by Django 5.2.5 on 2025-09-03 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_smsdevicekey_user'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepaymentmessage',
            name='verified_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_payment_message', to='core.invoice'),
        ),
    ]
