# Generated by Django 5.2.5 on 2025-08-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_storepaymentmessage_messager_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pid',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
