# Generated by Django 5.2.5 on 2025-08-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_basepaymentgateway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basepaymentgateway',
            name='app_key',
        ),
        migrations.RemoveField(
            model_name='basepaymentgateway',
            name='app_password',
        ),
        migrations.RemoveField(
            model_name='basepaymentgateway',
            name='app_secret',
        ),
        migrations.RemoveField(
            model_name='basepaymentgateway',
            name='app_username',
        ),
        migrations.AddField(
            model_name='basepaymentgateway',
            name='details_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basepaymentgateway',
            name='method',
            field=models.CharField(choices=[('bkash', 'bkash'), ('bkash-agent', 'bkash-agent'), ('bkash-personal', 'bkash-personal'), ('nagad', 'nagad'), ('nagad-agent', 'nagad-agent'), ('nagad-personal', 'nagad-personal'), ('rocket', 'rocket'), ('rocket-agent', 'rocket-agent'), ('rocket-personal', 'rocket-personal'), ('bank', 'bank'), ('crypto', 'crypto')], max_length=20),
        ),
    ]
