# Generated by Django 5.2.5 on 2025-08-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storepaymentmessage',
            name='messager_receiver',
        ),
    ]
