# Generated by Django 5.2.5 on 2025-08-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_basepaymentgateway_app_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepaymentgateway',
            name='base_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
