# Generated by Django 5.2.5 on 2025-09-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_storepaymentmessage_verified_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepaymentgateway',
            name='callback_base_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
