# Generated by Django 5.2.5 on 2025-09-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_basepaymentgateway_callback_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdevicekey',
            name='device_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
