# Generated by Django 5.2.5 on 2025-09-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_smsdevicekey_device_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='deposit_fees',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='payout_fees',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='withdraw_fees',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
