# Generated by Django 5.2.5 on 2025-08-19 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_smsdevicekey_storepaymentmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsdevicekey',
            name='device_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
