# Generated by Django 5.2.5 on 2025-08-19 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_smsdevicekey_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepaymentmessage',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_messages', to='authentication.smsdevicekey'),
        ),
    ]
