# Generated by Django 5.2.5 on 2025-08-19 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_storepaymentmessage_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsdevicekey',
            name='device_pin',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
